#!/usr/bin/env python3
"""
Test Groq Task Generation
Script to manually test Groq AI task generation
"""

import requests
import json
import sys

# Configuration
API_BASE_URL = "http://localhost:8000"
TEST_CLERK_ID = "test_user_123"  # Change this to your actual clerk ID

def test_groq_generation():
    """Test the Groq task generation endpoint"""
    
    print("\n" + "="*70)
    print("🤖 TESTING GROQ TASK GENERATION")
    print("="*70 + "\n")
    
    # Test data
    payload = {
        "clerkId": TEST_CLERK_ID,
        "userHealthData": {
            "age": 45,
            "firstName": "John",
            "conditions": ["diabetes", "hypertension"],
            "medications": ["Metformin", "Lisinopril"],
            "allergies": ["Penicillin"],
            "bloodPressure": "130/85",
            "bloodSugar": 150,
            "weight": 85,
            "activityLevel": "moderate"
        }
    }
    
    print(f"📤 Sending request to: {API_BASE_URL}/api/tasks/generate-groq")
    print(f"👤 User ID: {TEST_CLERK_ID}")
    print(f"📋 Health Data:")
    for key, value in payload["userHealthData"].items():
        print(f"   - {key}: {value}")
    print()
    
    try:
        # Make request
        response = requests.post(
            f"{API_BASE_URL}/api/tasks/generate-groq",
            json=payload,
            timeout=30
        )
        
        print(f"📊 Response Status: {response.status_code}")
        print(f"{'='*70}\n")
        
        if response.status_code == 200:
            data = response.json()
            
            print(f"✅ SUCCESS! Generated {len(data.get('tasks', []))} tasks\n")
            print(f"Message: {data.get('message')}\n")
            
            tasks = data.get('tasks', [])
            for idx, task in enumerate(tasks, 1):
                print(f"📌 Task {idx}:")
                print(f"   Title: {task.get('title')}")
                print(f"   Description: {task.get('description')}")
                print(f"   Category: {task.get('category')}")
                print(f"   Priority: {task.get('priority')}")
                print(f"   Generated by Groq: {task.get('generatedByGroq')}")
                print()
            
            print(f"{'='*70}")
            print(f"✅ TEST PASSED - All tasks generated successfully!")
            print(f"{'='*70}\n")
            
            return True
            
        else:
            print(f"❌ ERROR! Status code: {response.status_code}")
            print(f"\nResponse: {response.text}\n")
            return False
            
    except requests.exceptions.ConnectionError:
        print(f"❌ ERROR: Cannot connect to {API_BASE_URL}")
        print(f"Make sure the backend is running: uvicorn main:app --reload\n")
        return False
    except requests.exceptions.Timeout:
        print(f"❌ ERROR: Request timed out after 30 seconds")
        print(f"Groq API might be slow or the service might be down\n")
        return False
    except Exception as e:
        print(f"❌ ERROR: {str(e)}\n")
        return False

if __name__ == "__main__":
    # Allow custom clerk ID as argument
    if len(sys.argv) > 1:
        TEST_CLERK_ID = sys.argv[1]
    
    success = test_groq_generation()
    sys.exit(0 if success else 1)
