export default {
  name: 'dailyTask',
  type: 'document',
  title: 'Daily Task',
  fields: [
    {
      name: 'clerkId',
      type: 'string',
      title: 'Clerk User ID',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'title',
      type: 'string',
      title: 'Task Title',
      validation: (Rule: any) => Rule.required().max(200),
    },
    {
      name: 'description',
      type: 'text',
      title: 'Task Description',
    },
    {
      name: 'isCompleted',
      type: 'boolean',
      title: 'Is Completed',
      initialValue: false,
    },
    {
      name: 'priority',
      type: 'string',
      title: 'Priority',
      options: {
        list: [
          { title: 'Low', value: 'low' },
          { title: 'Medium', value: 'medium' },
          { title: 'High', value: 'high' },
        ],
      },
      initialValue: 'medium',
    },
    {
      name: 'category',
      type: 'string',
      title: 'Category',
      options: {
        list: [
          { title: 'Medication', value: 'medication' },
          { title: 'Exercise', value: 'exercise' },
          { title: 'Appointment', value: 'appointment' },
          { title: 'Health Check', value: 'health-check' },
          { title: 'Nutrition', value: 'nutrition' },
          { title: 'General', value: 'general' },
        ],
      },
      initialValue: 'general',
    },
    {
      name: 'dueDate',
      type: 'datetime',
      title: 'Due Date',
    },
    {
      name: 'completedAt',
      type: 'datetime',
      title: 'Completed At',
    },
    {
      name: 'generatedByGroq',
      type: 'boolean',
      title: 'Generated by Groq',
      initialValue: false,
    },
    {
      name: 'createdAt',
      type: 'datetime',
      title: 'Created At',
    },
    {
      name: 'updatedAt',
      type: 'datetime',
      title: 'Updated At',
    },
  ],
};
