/**
 * This file is auto-generated by sanity-typegen
 * Do not edit manually!
 */

export interface UserProfile {
  _id: string;
  _type: 'userProfile';
  clerkId: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  imageUrl?: string;
  bloodGroup?: string;
  age?: number;
  height?: number;
  weight?: number;
  chronicDiseases?: string;
  primaryLanguage?: string;
  caregiverName?: string;
  caregiverPhone?: string;
  highContrast?: boolean;
  largeTextMode?: boolean;
  reducedMotion?: boolean;
  voiceMode?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface OnboardingProgress {
  _id: string;
  _type: 'onboardingProgress';
  clerkId: string;
  welcomeCompleted?: boolean;
  healthInfoCompleted?: boolean;
  accessibilityCompleted?: boolean;
  permissionsCompleted?: boolean;
  onboardingCompleted?: boolean;
  currentStep?: 'welcome' | 'health-info' | 'accessibility' | 'permissions' | 'complete';
  startedAt?: string;
  completedAt?: string;
}

export interface MedicalReport {
  _id: string;
  _type: 'medicalReport';
  clerkId: string;
  reportType: 'blood-test' | 'xray' | 'ecg' | 'ultrasound' | 'ct-scan' | 'mri' | 'other';
  reportDate?: string;
  hospitalName?: string;
  doctorName?: string;
  findings?: string;
  reportFile?: {
    _type: 'file';
    asset: {
      _ref: string;
      _type: 'reference';
    };
  };
  uploadedAt?: string;
}

export type SanityDocument = UserProfile | OnboardingProgress | MedicalReport;
